<?php

namespace YoussefMekkkawy\LaravelAiTranslator\Services\Writers;

use Illuminate\Support\Facades\File;
use YoussefMekkkawy\LaravelAiTranslator\Services\Backup\BackupService;
use Carbon\Carbon;

class LanguageFileWriter
{
    /**
     * Backup service instance
     */
    protected BackupService $backupService;

    /**
     * Configuration
     */
    protected array $config;

    /**
     * Constructor
     */
    public function __construct(BackupService $backupService, array $config = [])
    {
        $this->backupService = $backupService;
        $this->config = $config;
    }

    /**
     * Write translations to a language file
     *
     * @param string $lang Language code (e.g., 'ar', 'fr')
     * @param string $file File name without .php (e.g., 'auth', 'welcome')
     * @param array $translations Key-value pairs to write
     * @param bool $merge Merge with existing or replace (default: merge)
     * @return string Path to the written file
     */
    public function write(string $lang, string $file, array $translations, bool $merge = true): string
    {
        $filePath = $this->getFilePath($lang, $file);

        // Backup existing file if it exists
        if (File::exists($filePath) && $this->backupService->isEnabled()) {
            $this->backupService->backupFile($filePath);
        }

        // Load existing translations if merging
        $existingTranslations = [];
        if ($merge && File::exists($filePath)) {
            $existingTranslations = include $filePath;
            if (!is_array($existingTranslations)) {
                $existingTranslations = [];
            }
        }

        // Merge translations (new values override existing)
        $finalTranslations = $merge 
            ? array_merge($existingTranslations, $translations)
            : $translations;

        // Generate PHP file content
        $content = $this->generateFileContent($finalTranslations);

        // Ensure directory exists
        $this->ensureDirectoryExists(dirname($filePath));

        // Write to file
        File::put($filePath, $content);

        return $filePath;
    }

    /**
     * Write translations for multiple files at once
     *
     * @param string $lang Language code
     * @param array $fileTranslations ['file' => ['key' => 'value']]
     * @return array Paths to written files
     */
    public function writeMultiple(string $lang, array $fileTranslations): array
    {
        $writtenFiles = [];

        foreach ($fileTranslations as $file => $translations) {
            $writtenFiles[$file] = $this->write($lang, $file, $translations);
        }

        return $writtenFiles;
    }

    /**
     * Generate PHP file content with proper formatting
     *
     * @param array $translations
     * @return string
     */
    protected function generateFileContent(array $translations): string
    {
        $header = $this->generateHeader();
        $arrayContent = $this->arrayToPhp($translations);

        return "<?php\n\n{$header}\nreturn {$arrayContent};\n";
    }

    /**
     * Generate file header with auto-generated notice
     */
    protected function generateHeader(): string
    {
        $timestamp = Carbon::now()->format('Y-m-d H:i:s');

        return <<<HEADER
/*
|--------------------------------------------------------------------------
| Auto-generated Translation File
|--------------------------------------------------------------------------
|
| This file was automatically generated by Laravel AI Translator.
| Last updated: {$timestamp}
|
| ⚠️  WARNING: Do not edit this file manually!
| ⚠️  Use 'php artisan lang:lock' to protect custom translations.
|
*/
HEADER;
    }

    /**
     * Convert array to properly formatted PHP code
     *
     * @param array $array
     * @param int $depth Indentation depth
     * @return string
     */
    protected function arrayToPhp(array $array, int $depth = 0): string
    {
        if (empty($array)) {
            return '[]';
        }

        $indent = str_repeat('    ', $depth);
        $nextIndent = str_repeat('    ', $depth + 1);
        
        $lines = ["["];

        foreach ($array as $key => $value) {
            $formattedKey = $this->formatKey($key);
            
            if (is_array($value)) {
                // Nested array
                $formattedValue = $this->arrayToPhp($value, $depth + 1);
                $lines[] = "{$nextIndent}{$formattedKey} => {$formattedValue},";
            } else {
                // Simple value
                $formattedValue = $this->formatValue($value);
                $lines[] = "{$nextIndent}{$formattedKey} => {$formattedValue},";
            }
        }

        $lines[] = "{$indent}]";

        return implode("\n", $lines);
    }

    /**
     * Format array key for PHP output
     */
    protected function formatKey($key): string
    {
        return "'" . addslashes($key) . "'";
    }

    /**
     * Format value for PHP output
     */
    protected function formatValue($value): string
    {
        if ($value === null) {
            return 'null';
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (is_numeric($value)) {
            return (string) $value;
        }

        // String - escape properly
        return "'" . addslashes($value) . "'";
    }

    /**
     * Get full file path for a language file
     */
    protected function getFilePath(string $lang, string $file): string
    {
        $langPath = base_path('lang');
        return $langPath . DIRECTORY_SEPARATOR . $lang . DIRECTORY_SEPARATOR . $file . '.php';
    }

    /**
     * Ensure directory exists, create if not
     */
    protected function ensureDirectoryExists(string $path): void
    {
        if (!File::exists($path)) {
            File::makeDirectory($path, 0755, true);
        }
    }

    /**
     * Check if a language file exists
     */
    public function exists(string $lang, string $file): bool
    {
        return File::exists($this->getFilePath($lang, $file));
    }

    /**
     * Read translations from a language file
     */
    public function read(string $lang, string $file): array
    {
        $filePath = $this->getFilePath($lang, $file);

        if (!File::exists($filePath)) {
            return [];
        }

        $translations = include $filePath;

        return is_array($translations) ? $translations : [];
    }

    /**
     * Delete a language file
     */
    public function delete(string $lang, string $file): bool
    {
        $filePath = $this->getFilePath($lang, $file);

        if (!File::exists($filePath)) {
            return false;
        }

        // Backup before deleting
        if ($this->backupService->isEnabled()) {
            $this->backupService->backupFile($filePath);
        }

        return File::delete($filePath);
    }

    /**
     * Get all translation files for a language
     */
    public function getFiles(string $lang): array
    {
        $langPath = base_path('lang') . DIRECTORY_SEPARATOR . $lang;

        if (!File::exists($langPath)) {
            return [];
        }

        $files = File::files($langPath);
        $fileNames = [];

        foreach ($files as $file) {
            if ($file->getExtension() === 'php') {
                $fileNames[] = $file->getBasename('.php');
            }
        }

        return $fileNames;
    }

    /**
     * Organize translations by file
     * Input: ['auth.login' => 'value', 'welcome.title' => 'value']
     * Output: ['auth' => ['login' => 'value'], 'welcome' => ['title' => 'value']]
     */
    public function organizeByFile(array $flatTranslations): array
    {
        $organized = [];

        foreach ($flatTranslations as $fullKey => $value) {
            // Split key into file and key parts
            $parts = explode('.', $fullKey, 2);
            
            if (count($parts) === 1) {
                // No dot in key, put in 'auto.php'
                $file = 'auto';
                $key = $parts[0];
            } else {
                $file = $parts[0];
                $key = $parts[1];
            }

            // Handle nested keys (e.g., auth.password.reset)
            if (strpos($key, '.') !== false) {
                $organized[$file] = $this->setNestedValue(
                    $organized[$file] ?? [],
                    $key,
                    $value
                );
            } else {
                $organized[$file][$key] = $value;
            }
        }

        return $organized;
    }

    /**
     * Set nested array value using dot notation
     */
    protected function setNestedValue(array $array, string $key, $value): array
    {
        $keys = explode('.', $key);
        $current = &$array;

        foreach ($keys as $i => $k) {
            if ($i === count($keys) - 1) {
                $current[$k] = $value;
            } else {
                if (!isset($current[$k]) || !is_array($current[$k])) {
                    $current[$k] = [];
                }
                $current = &$current[$k];
            }
        }

        return $array;
    }

    /**
     * Create backup of all language files
     */
    public function backupAll(): string
    {
        return $this->backupService->backup();
    }

    /**
     * List all available backups
     */
    public function listBackups(): array
    {
        return $this->backupService->listBackups();
    }

    /**
     * Restore from a backup
     */
    public function restore(string $timestamp): bool
    {
        return $this->backupService->restore($timestamp);
    }
}