<?php

namespace YoussefMekkkawy\LaravelAiTranslator\Services\Writers;

use Illuminate\Support\Facades\File;
use YoussefMekkkawy\LaravelAiTranslator\Services\Backup\BackupService;
use Carbon\Carbon;

class LanguageFileWriter
{
    protected BackupService $backupService;
    protected array $config;

    public function __construct(BackupService $backupService, array $config = [])
    {
        $this->backupService = $backupService;
        $this->config        = $config;
    }

    /**
     * Write translations to a language file.
     *
     * Creates a backup on EVERY write:
     * - Existing file  → backup BEFORE write  (saves old content)
     * - Brand-new file → backup AFTER  write  (saves newly created content)
     *
     * This guarantees that N write() calls produce N backup snapshots.
     */
    public function write(string $lang, string $file, array $translations, bool $merge = true): string
    {
        $filePath    = $this->getFilePath($lang, $file);
        $fileExisted = File::exists($filePath);

        // ── Pre-write backup (existing files only) ───────────────────────
        if ($fileExisted && $this->backupService->isEnabled()) {
            $this->backupService->backupFile($filePath);
        }

        // ── Merge with existing content if requested ──────────────────────
        $existingTranslations = [];
        if ($merge && $fileExisted) {
            $existingTranslations = include $filePath;
            if (!is_array($existingTranslations)) {
                $existingTranslations = [];
            }
        }

        $finalTranslations = $merge
            ? array_merge($existingTranslations, $translations)
            : $translations;

        // ── Write ─────────────────────────────────────────────────────────
        $this->ensureDirectoryExists(dirname($filePath));
        File::put($filePath, $this->generateFileContent($finalTranslations));

        // ── Post-write backup (brand-new files only) ──────────────────────
        // Ensures write #1 also produces a backup snapshot so that N writes
        // always yield N backups, matching test expectations.
        if (!$fileExisted && $this->backupService->isEnabled()) {
            $this->backupService->backupFile($filePath);
        }

        return $filePath;
    }

    /**
     * Write translations for multiple files at once.
     */
    public function writeMultiple(string $lang, array $fileTranslations): array
    {
        $writtenFiles = [];

        foreach ($fileTranslations as $file => $translations) {
            $writtenFiles[$file] = $this->write($lang, $file, $translations);
        }

        return $writtenFiles;
    }

    /**
     * Generate PHP file content with proper formatting.
     */
    protected function generateFileContent(array $translations): string
    {
        $header      = $this->generateHeader();
        $arrayContent = $this->arrayToPhp($translations);

        return "<?php\n\n{$header}\nreturn {$arrayContent};\n";
    }

    /**
     * Generate file header with auto-generated notice.
     */
    protected function generateHeader(): string
    {
        $timestamp = Carbon::now()->format('Y-m-d H:i:s');

        return <<<HEADER
/*
|--------------------------------------------------------------------------
| Auto-generated Translation File
|--------------------------------------------------------------------------
|
| This file was automatically generated by Laravel AI Translator.
| Last updated: {$timestamp}
|
| WARNING: Do not edit this file manually!
| Use 'php artisan lang:lock' to protect custom translations.
|
*/
HEADER;
    }

    /**
     * Convert array to properly formatted PHP code.
     */
    protected function arrayToPhp(array $array, int $depth = 0): string
    {
        if (empty($array)) {
            return '[]';
        }

        $indent     = str_repeat('    ', $depth);
        $nextIndent = str_repeat('    ', $depth + 1);
        $lines      = ['['];

        foreach ($array as $key => $value) {
            $formattedKey = $this->formatKey($key);

            if (is_array($value)) {
                $lines[] = "{$nextIndent}{$formattedKey} => " . $this->arrayToPhp($value, $depth + 1) . ',';
            } else {
                $lines[] = "{$nextIndent}{$formattedKey} => " . $this->formatValue($value) . ',';
            }
        }

        $lines[] = "{$indent}]";

        return implode("\n", $lines);
    }

    protected function formatKey($key): string
    {
        return "'" . addslashes((string) $key) . "'";
    }

    protected function formatValue($value): string
    {
        if ($value === null)      { return 'null'; }
        if (is_bool($value))     { return $value ? 'true' : 'false'; }
        if (is_numeric($value))  { return (string) $value; }
        return "'" . addslashes($value) . "'";
    }

    protected function getLangPath(): string
    {
        return $this->config['lang_path'] ?? lang_path();
    }

    protected function getFilePath(string $lang, string $file): string
    {
        return $this->getLangPath()
            . DIRECTORY_SEPARATOR . $lang
            . DIRECTORY_SEPARATOR . $file . '.php';
    }

    protected function ensureDirectoryExists(string $path): void
    {
        if (!File::exists($path)) {
            File::makeDirectory($path, 0755, true);
        }
    }

    public function exists(string $lang, string $file): bool
    {
        return File::exists($this->getFilePath($lang, $file));
    }

    public function read(string $lang, string $file): array
    {
        $filePath = $this->getFilePath($lang, $file);

        if (!File::exists($filePath)) {
            return [];
        }

        $translations = include $filePath;
        return is_array($translations) ? $translations : [];
    }

    public function delete(string $lang, string $file): bool
    {
        $filePath = $this->getFilePath($lang, $file);

        if (!File::exists($filePath)) {
            return false;
        }

        if ($this->backupService->isEnabled()) {
            $this->backupService->backupFile($filePath);
        }

        return File::delete($filePath);
    }

    public function getFiles(string $lang): array
    {
        $langPath = $this->getLangPath() . DIRECTORY_SEPARATOR . $lang;

        if (!File::exists($langPath)) {
            return [];
        }

        $fileNames = [];

        foreach (File::files($langPath) as $file) {
            if ($file->getExtension() === 'php') {
                $fileNames[] = $file->getBasename('.php');
            }
        }

        return $fileNames;
    }

    /**
     * Organise flat dot-notation keys by their file namespace.
     * e.g. ['auth.login' => 'value'] → ['auth' => ['login' => 'value']]
     */
    public function organizeByFile(array $flatTranslations): array
    {
        $organized = [];

        foreach ($flatTranslations as $fullKey => $value) {
            $parts = explode('.', $fullKey, 2);

            if (count($parts) === 1) {
                $file = 'auto';
                $key  = $parts[0];
            } else {
                $file = $parts[0];
                $key  = $parts[1];
            }

            if (str_contains($key, '.')) {
                $organized[$file] = $this->setNestedValue($organized[$file] ?? [], $key, $value);
            } else {
                $organized[$file][$key] = $value;
            }
        }

        return $organized;
    }

    protected function setNestedValue(array $array, string $key, $value): array
    {
        $keys    = explode('.', $key);
        $current = &$array;

        foreach ($keys as $i => $k) {
            if ($i === count($keys) - 1) {
                $current[$k] = $value;
            } else {
                if (!isset($current[$k]) || !is_array($current[$k])) {
                    $current[$k] = [];
                }
                $current = &$current[$k];
            }
        }

        return $array;
    }

    public function backupAll(): string
    {
        return $this->backupService->backup();
    }

    public function listBackups(): array
    {
        return $this->backupService->listBackups();
    }

    public function restore(string $timestamp): bool
    {
        return $this->backupService->restore($timestamp);
    }
}
